### ISSUE TITLE
PA/PB 프로필 Main UI

### ISSUE THREAD

**Issue by oneStar92** [Team-BrewBuds/FE_REPO#23]
## 어떤 기능인가요?
PA, PB 프로필 Main UI

## ToDo List
- [ ] 공통된 Widget 구현
- [ ] PA 프로필 UI
- [ ] PB 프로필 UI
